image: maven:3.3.9-jdk-8

before_script:
  - |
    cd /builds/earl/jmeter-tests
    echo 'export LT_USERNAME=<username>' >> ~/.bashrc
    echo 'export LT_ACCESS_KEY=<access key>' >> ~/.bashrc

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn compile
  tags:
    - cluster
    - kubernetes
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

test:
  stage: test
  script:
    - mvn clean test
  tags:
    - cluster
    - kubernetes
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
